# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0002_auto_20170827_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-title']},
        ),
    ]
