# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to='photo/%Y/%m'),
        ),
    ]
