# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20170824_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m'),
        ),
    ]
